### ISSUE TITLE
FAQ content is not displayed when initiated by a Button / QR click

### ISSUE THREAD

**Issue by ashu2390** [scupid-admin/Morph.ai-Support#105]
Brand ID: healthcarefn1br

**Comment by ashu2390** [comment]
Not happening for all FAQs, like 'What's a network' FAQ is giving content fine when initiated by a button click from 'Frequent Questions' conversation.

**Comment by snehalseth** [comment]
This issue is due to duplicate conversation created when faq is edited. It has been fixed now from UI.
But we need to delete duplicate conversation, and reselect the FAQ conversations wherever used.
@vidzi lets discuss this on how we will do it.

**Comment by vidzi** [comment]
This was fixed. 
Please reopen @ashu2390 if the issue persists.
