### ISSUE TITLE
10 digit phone no. - system is still considering it invalid - healthcarefn1br

### ISSUE THREAD

**Issue by ashu2390** [scupid-admin/Morph.ai-Support#114]
3122969191 - This no. is being considered, though this is of a person in USA; tried with another random 10 digit no. starting with '3' - also considered invalid. But some nos. are working fine.

![screen shot 2018-10-29 at 11 12 35 pm](https://user-images.githubusercontent.com/42344797/47669129-309bd680-dbd0-11e8-9c7c-c000e79866fb.png)

**Comment by deemorph** [comment]
@ashu2390 
Fixed. Changes are deployed on production. Can you please check from your side also?

**Comment by vidzi** [comment]
@ashu2390 closing this. please re-open if issue persists.
