### ISSUE TITLE
intent not opening issue

### ISSUE THREAD

**Issue by sodium23** [scupid-admin/Morph.ai-Support#25]
"i creat this intent but when i click on it, it's not open!
![pasted image at 2017_08_22 12_23 pm](https://user-images.githubusercontent.com/14252312/29556788-92e0ccec-8744-11e7-9a69-568b6671ab1e.png)
"

**Comment by inuishan** [comment]
انواع شرط is another example

**Comment by sodium23** [comment]
issue has been fixed
