### ISSUE TITLE
Unable to make API call using user attributes

### ISSUE THREAD

**Issue by knoxxs** [scupid-admin/Morph.ai-Support#26]
![websericewithcustomparameters](https://user-images.githubusercontent.com/1270959/29554853-4fbb0d3e-873e-11e7-9109-bc2c0830e9a2.png)

**Comment by Deepak54321** [comment]
1. My bot ID: RakeshKumar@yamaha-motor-india.com.
2. My conversation name : Webapicall1.

**Comment by sodium23** [comment]
issue resolved
