### ISSUE TITLE
How to webapi parsed result in bot.

### ISSUE THREAD

**Issue by Deepak54321** [scupid-admin/Morph.ai-Support#27]
We have  used your code module in my conversation webapicall1 with login Rakeshkumar-yamaha-motor-india.com but still code not work for me and i just want to read a  web service data and try to show in statements(text+button).

**Comment by inuishan** [comment]
Import messages are missing. 

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import morph.base.beans.CustomCodeResponse;

Only these are the import statements. 

Please make sure the project is compiling locally by doing gradle build. Copy the whole code including the import statements.

**Comment by inuishan** [comment]
Closing this issue, If you still face issues after including import statements, please re-open this & let us know.

**Comment by Deepak54321** [comment]
from my side issue is still open i have build the code successfully using gradle build but it's not working at all and this time  i take the code with all references but bot still gives me error and i have send all the screen shorts to your chat support.

**Comment by Deepak54321** [comment]
Dear Ishan,
I have send you all the screen shorts to your chat support as well you can download them from email and from my side issue is still open.
Thanks & Regards
Deepak Mishra
Software Engineer

**Comment by inuishan** [comment]
You are not returning anything from the method. That's why it is not working. Please refer to documentation https://docs.morph.ai/dashboard/build/conversations/modules/custom-code/java.html

**Comment by Deepak54321** [comment]
Dear Ishan,
I have set the return object to custom code response object but stil error remains same I am going to discuss the procedure that I am following to put code in code module first I am writing the code in eclipse and then do gradle build when it build successfully then I copy the code and paste in code module.
Thanks & regards
Deepak Mishra

**Comment by Deepak54321** [comment]
Now I have return the CustomCodeResponse object output remains same and still i am getting errors instead of data on bot.
