### ISSUE TITLE
[Web Messenger] Image rendering and close icon in Image preview needs improvement

### ISSUE THREAD

**Issue by sodium23** [scupid-admin/Morph.ai-Support#31]
The cross icon in the image preview for web messenger appears as a patch and needs to be changed

**Comment by vipul261** [comment]
`c670064` [WEB-MESSENGER] Fixes image preview styles - Vipul Garg
`2e471a0` [WEB-MESSENGER] Changes close icon to embedded svg - Vipul Garg

Fixed aspect ratio of image rendering and close icon
