### ISSUE TITLE
Matching is not working correctly

### ISSUE THREAD

**Issue by knoxxs** [scupid-admin/Morph.ai-Support#4]
1. Enquiring about plan and BoT is giving wrong response. (tell me my plan, my number is 9624799165)
2. Incorrect responses to my queries on Facebook. (Hi, can you tell me about my plan details)
3. Incorrect responses to my queries on Facebook. (Configuration required)
4. Recharge Information reflecting in Postpaid.
5.

**Comment by jayeshathila** [comment]
1.Enquiring about plan and BoT is giving wrong response. (tell me my plan, my number is 9624799165)
**Status**: Now given sentence not giving wrong response , to know about plan query:"active plans"

2. Incorrect responses to my queries on Facebook. (Hi, can you tell me about my plan details)
**Status**: Response seems to be relevant (@aapa ek baar verify kar lena , though I will debug and tell kaunse se match kiya)

3.Incorrect responses to my queries on Facebook. (Configuration required)
**Status**: Now given sentence not giving wrong response , to change Configuration  query:"change network configuration"
