### ISSUE TITLE
Announcement issue: IIFL - wwwicicibaesepj

### ISSUE THREAD

**Issue by ashu2390** [scupid-admin/Morph.ai-Support#56]
Announcements sent were not received by me, Niyati and Abhishek, although it went fine all other users. Titles of announcements are:

Subscription content - 14/08/2018
Subscription content - 15/08/2018

**Comment by deemorph** [comment]
For Subscription content - 14/08/2018

Customer Search Query:
{ "interfaceAccounts.channel" : { "$in" : [ "facebook" ] }, "iVPV.___isBlckd" : false, "iVPV.___bIAK.vs" : { "$in" : [ "facebook___634438273363526"]}, "iVPV._5b6ecf11e1a7541d78aae7e2" : { "$exists" : true}, "isDeleted" : false }

Page Id: 634438273363526
Property Id: _5b6ecf11e1a7541d78aae7e2 (Name/Title: Subscribed)

Number of customers found using query: 83


Queries to search mentioned customers:

{ "interfaceAccounts.channel" : { "$in" : [ "facebook" ] }, "iVPV.___isBlckd" : false, "iVPV.___bIAK.vs" : { "$in" : [ "facebook___634438273363526"]}, "isDeleted" : false, "iVPV.___nm": /Niyati Agarwal/i }


{ "interfaceAccounts.channel" : { "$in" : [ "facebook" ] }, "iVPV.___isBlckd" : false, "iVPV.___bIAK.vs" : { "$in" : [ "facebook___634438273363526"]}, "isDeleted" : false, "iVPV.___nm": /Abhishek Gupta/i }

{ "interfaceAccounts.channel" : { "$in" : [ "facebook" ] }, "iVPV.___isBlckd" : false, "iVPV.___bIAK.vs" : { "$in" : [ "facebook___634438273363526"]}, "isDeleted" : false, "iVPV.___nm": /Ashutosh Sharma/i }

{ "interfaceAccounts.channel" : { "$in" : [ "facebook" ] }, "iVPV.___isBlckd" : false, "iVPV.___bIAK.vs" : { "$in" : [ "facebook___634438273363526"]}, "isDeleted" : false, "iVPV.___nm": /Pratik Jain/i }


Property(_5b6ecf11e1a7541d78aae7e2) not set: Niyati, Ashutosh, Pratik

Customers not found: Abhishek

**Comment by knoxxs** [comment]
This was not a bug. The right props were not set.
