### ISSUE TITLE
MOSL: Workflow not working #urgent

### ISSUE THREAD

**Issue by scupid-admin** [scupid-admin/Morph.ai-Support#57]
Due to deletion of nodes in workflow, customers are not getting workflow messages

**Comment by knoxxs** [comment]
Total customers: 476

```js

var allC = db.schedulableTask.distinct("cKey", {
    "createdTime": {"$gt": 1533459741000},
    "tType": "workflow",
    "convId": "5afff2e7e1a75469d759fcfa",
    "iActv": false
});
var issuefulC = [];
allC.forEach(function (cKey) {
    var task = db.schedulableTask.find({
        "cKey": cKey,
        "tType": "workflow",
        "convId": "5afff2e7e1a75469d759fcfa",
        "iActv": false
    }).sort({createdTime: -1}).limit(1).toArray()[0];

    var node = db.conversationNode.findOne({_id: ObjectId(task["convNId"])});
    if (node !== null && node["iD"]) {
        node = null;
    }

    if (node === null) {
        issuefulC.push(cKey);
    }
});

var issuefulCVsCount = {};
issuefulC.forEach(function (cKey) {
    issuefulCVsCount[cKey] = db.schedulableTask.count({
        "cKey": cKey,
        "tType": "workflow",
        "convId": "5afff2e7e1a75469d759fcfa"
    });
});

var countVsNewNodeId = {1: "5afff290ae11d7c3fe7b6295", 2: "5b76568f114fee5c6de9eda7", 3: "5b7656ad09421a03b2239416", 4: "5afff2ab00dda6ec53ffc919", 5: "5afff2b2037a704a31452d61", 6: "5afff2bb4c47f5f68cd8595c", 7: "5afff2db07a018c251920bd9"};

for (var cKey in issuefulCVsCount) {
    var newNodeId = countVsNewNodeId[issuefulCVsCount[cKey]];

    var task = db.schedulableTask.find({
        "cKey": cKey,
        "tType": "workflow",
        "convId": "5afff2e7e1a75469d759fcfa",
        "iActv": false
    }).sort({createdTime: -1}).limit(1).toArray()[0];

    task["convNId"] = newNodeId;
    task["isActv"] = true;

    if (non_debug_mode) {
        db.schedulableTask.save(task);
    }else{
        print("Will save:");
        printjson(task);
    }
}
```

**Comment by knoxxs** [comment]
Workflow:
```
5afff290ae11d7c3fe7b6295 WORKFLOW_DELAY
5b76568f114fee5c6de9eda7 CONDITIONAL_V2
--Not unsubscribed--Starting
--Not unsubscribed--5b7656a1bba80b6fd90e66a3 JUMP
--Default--Starting
5afff29b5f889efb4b09c01a WORKFLOW_DELAY
5b7656ad09421a03b2239416 CONDITIONAL_V2
--Not Unsubscribed--Starting
--Not Unsubscribed--5b7656bc21897ba1c46097a5 JUMP
--Default--Starting
5afff2ab00dda6ec53ffc919 WORKFLOW_DELAY
5b7656c9696c038e54f703fc CONDITIONAL_V2
--Not Subscribed--Starting
--Not Subscribed--5b7656d72e5d5118d52ba4f8 JUMP
--Default--Starting
5afff2b2037a704a31452d61 WORKFLOW_DELAY
5b7656e3bf2258a6dacbe5d2 CONDITIONAL_V2
--Not Unsubscribed--Starting
--Not Unsubscribed--5b7656f199fe9ec09107a730 JUMP
--Default--Starting
5afff2bb4c47f5f68cd8595c WORKFLOW_DELAY
5b7657009a6d2d480383b8f8 CONDITIONAL_V2
--Not Unsubscribed--Starting
--Not Unsubscribed--5b76570eacc4cd6518b4b659 JUMP
--Default--Starting
5afff2db07a018c251920bd9 WORKFLOW_DELAY
5b765718292f8607490d9cc5 CONDITIONAL_V2
--Not Subscribed--Starting
--Not Subscribed--5b765726fd5d3374c1c0ff41 JUMP
--Default--Starting
```

**Comment by vidzi** [comment]
Final Script that was run:

`var issuefulC = ["facebook___1797171033672059", 	"facebook___1703467133081849", 	"facebook___2171511606211097", 	"facebook___2183422788366044", 	"facebook___1765981990166460", 	"facebook___3027037577394396", 	"facebook___1824590357656138", 	"facebook___2265671236796134", 	"facebook___2241898045839327", 	"facebook___1921203097930265", 	"facebook___1801786203274904", 	"facebook___2125905834150912", 	"facebook___2266478273367640", 	"facebook___2082854835072674", 	"facebook___1887247977979895", 	"facebook___1802800593173795", 	"facebook___1870749919627910", 	"facebook___2361657443859565", 	"facebook___1828794537200715", 	"facebook___1913701908695460", 	"facebook___2511260525551574", 	"facebook___2358058547552468", 	"facebook___1826875200764771", 	"facebook___2159259707449797", 	"facebook___2330007330372977", 	"facebook___1776201872495226", 	"facebook___1939546459421498", 	"facebook___1643434492433362", 	"facebook___2290401661000060", 	"facebook___1780474558667572", 	"facebook___1900768279965958", 	"facebook___1752815484788317", 	"facebook___1945054795540801", 	"facebook___1664289930360471", 	"facebook___1777903428983117", 	"facebook___1902405513179793", 	"facebook___1855219454515555", 	"facebook___1954512374591893", 	"facebook___1792400480829071", 	"facebook___1990215471023819", 	"facebook___1836517499760660", 	"facebook___1845859502172684", 	"facebook___1796288280491140", 	"facebook___1718517374862190", 	"facebook___1809992669090732", 	"facebook___2660504797308638", 	"facebook___1877681338955348", 	"facebook___2270258406337535", 	"facebook___1835826339799631", 	"facebook___1767823853330253", 	"facebook___1823967954359739", 	"facebook___1831790770243804", 	"facebook___2471054439602150", 	"facebook___2079350378741973", 	"facebook___1643251635785619", 	"facebook___1971962856159024", 	"facebook___1974867025869219", 	"facebook___2004038782981651", 	"facebook___2006093852763629", 	"facebook___1822679604492394", 	"facebook___1750577181705194", 	"facebook___2066885903375670", 	"facebook___2298414300174012", 	"facebook___2555101984516102", 	"facebook___1805753419505955", 	"facebook___1604603372978316", 	"facebook___2156041584440386", 	"facebook___1775705329150697", 	"facebook___2052150284794978", 	"facebook___1445989298834081", 	"facebook___1326449860790999", 	"facebook___1857205714326850", 	"facebook___1817329841669104", 	"facebook___2117369498336966", 	"facebook___2119201434817713", 	"facebook___2161030937305031", 	"facebook___2022989594412752", 	"facebook___2047213148656913", 	"facebook___1380931452010389", 	"facebook___2125383334198935", 	"facebook___1851337648291297", 	"facebook___1655575904546440", 	"facebook___1967460056649695", 	"facebook___2012115805489208"];


var issuefulCVsCount = {};
issuefulC.forEach(function (cKey) {
    issuefulCVsCount[cKey] = db.schedulableTask.count({
        "cKey": cKey,
        "tType": "workflow",
        "convId": "5afff2e7e1a75469d759fcfa"
    });
});

var countVsNewNodeId = {1: "5afff290ae11d7c3fe7b6295", 2: "5b76568f114fee5c6de9eda7", 3: "5b7656ad09421a03b2239416", 4: "5afff2ab00dda6ec53ffc919", 5: "5afff2b2037a704a31452d61", 6: "5afff2bb4c47f5f68cd8595c", 7: "5afff2db07a018c251920bd9"};

for (var cKey in issuefulCVsCount) {
    var newNodeId = countVsNewNodeId[issuefulCVsCount[cKey]];

    var task = db.schedulableTask.find({
        "cKey": cKey,
        "tType": "workflow",
        "convId": "5afff2e7e1a75469d759fcfa",
        "iActv": false
    }).sort({createdTime: -1}).limit(1).toArray()[0];

    task["convNId"] = newNodeId;
    task["iActv"] = true;

    if (non_debug_mode) {
        db.schedulableTask.save(task);
    }else{
        print("Will save:");
        printjson(task);
    }
}`
