### ISSUE TITLE
Ad Leads who write a message without clicking on get started button

### ISSUE THREAD

**Issue by scupid-admin** [scupid-admin/Morph.ai-Support#59]
"Most of my leads post their question on the chat without clicking on the Get started button in message template. Is there a better way to indicate them to click or a workaround" - skillSanta

**Comment by knoxxs** [comment]
This is a pretty big task for the product. Also, we don't even have a solution yet. Will be working on it next week. Because we don't have a solution yet, there is a chance we won't be able to run bot for such users in real time.

**Comment by sodium23** [comment]
hmmm ok keep me updated

**Comment by sodium23** [comment]
https://scupid.slack.com/archives/G10HFGFPD/p1536314739000100

```
We have added the support for tackling non-cta ad user.
We will need to change configurations for this.
https://github.com/scupid-admin/morph/wiki/Configure-Ad-Ref
```
