### ISSUE TITLE
Dynamic Quick Reply 

### ISSUE THREAD

**Issue by scupid-admin** [scupid-admin/Morph.ai-Support#60]

**Comment by sodium23** [comment]
If I give user a quick reply with 5 options after him selecting one I want the same quick reply to appear with either only 4 options or same 5 options again with recently clicked option pushed to last.

**Comment by knoxxs** [comment]
Need to understand the actual requirement. The above-mentioned thing is a solution.

**Comment by sodium23** [comment]
Lets discuss it today, have one urgent requirement around this

**Comment by sodium23** [comment]
Whatsapp form bot needs multi-select

**Comment by vidzi** [comment]
As discussed with @knoxxs, this will be prioritised soon as a feature.

**Comment by vidzi** [comment]
Have added this in my product task sheet. Closing it for now.
