### ISSUE TITLE
Conversation is not getting triggered  #urgent

### ISSUE THREAD

**Issue by sodium23** [scupid-admin/Morph.ai-Support#65]
When triggering conversation through refferal, nothings happening 

conversation: share button testing
user: niyati agarwal
brand: morph
referral: https://m.me/560919760736374?ref=___cRf-_-share

**Comment by knoxxs** [comment]
There is a Bot Says which has Text message and a share button.

Share button can only come with 
- Generic template
- List template
- Media template

**Comment by knoxxs** [comment]
@vipul261 need to put this validation in UI

**Comment by sodium23** [comment]
ok

**Comment by sodium23** [comment]
@vipul261 Is this done? If not then add it in your tasks, closing this issue now.

--aapa here
