### ISSUE TITLE
Export Button Issue - #URGENT

### ISSUE THREAD

**Issue by ayushmittal29** [scupid-admin/Morph.ai-Support#71]
Export button, should send out the extract to the respective email id attached to the login credentials, but the extract is not getting Delivered.

**Comment by knoxxs** [comment]
Vidisha [22 hours ago]
will check


Vidisha [22 hours ago]
@Deepak can u please check this error once?


Deepak [21 hours ago]
Fixed.
 


Ayush [21 hours ago]
Thanks.. :+1:
