### ISSUE TITLE
Not getting 'Announce' permission in superagent mode ( wwwnestleiq9wqk )

### ISSUE THREAD

**Issue by ashu2390** [scupid-admin/Morph.ai-Support#77]
Initially, a parallel login in incognito mode for the same brand's superagent was working while in a normal window it was not working. Now its not working in incognito mode as well.

Happening only in selected brands, while in others I have that announce permission.

**Comment by deemorph** [comment]
Fixed.

**Comment by deemorph** [comment]
Fixed and deployed on prod
