### ISSUE TITLE
Issues faced by Sales Team: UNSET

### ISSUE THREAD

**Issue by ayushmittal29** [scupid-admin/Morph.ai-Support#84]
In the carousel buttons - Tried unsetting a property along with Jumping to another conversation. The property was not cleared but updated with the value as '__UNSET__'

**Comment by deemorph** [comment]
Fixed. Currently changes are on develop.

**Comment by sodium23** [comment]
@vidzi

**Comment by deemorph** [comment]
Changes sent to production.
