### ISSUE TITLE
API Integration for Max Life insurance

### ISSUE THREAD

**Issue by ayushmittal29** [scupid-admin/Morph.ai-Support#89]
API Integration for Max Life insurance

{

  "request": {

    "header": {

      "soaMsgVersion": "1.0",

      "soaCorrelationId": "49d28623-981b-4e60-8d47-525df4485b6b",

      "soaPassword": "bmVvQDEyMw\u003d\u003d",

      "soaUserId": "NEO123",

      "soaAppId": "NEO"

    },

    "requestData": {

      "createLeadWithRider": [

        {

          "lead": {

            "leadOwnerKey": "1",

            "leadAmount": "50000",

            "leadName": "Gdgfd",

            "statusCodeDisplay": "New Lead",

            "leadAction": "add",

            "applicationStatus": "109",

            "applicationSubStatus": "112",

            "productCode": "TCOTP2",

            "statusCode": "123",

            "product": "",

            "influencerCategory": "Website Direct",

            "influencerCompanyCode": "4",

            "influencerSourceCode": "178",

            "leadSource": "250",

            "ratingKey": "1"

          },

          "proposer": {

            "email": "ddd@gggg.vom",

            "firstName": "Gdgfd",

            "mobilePhone": "9787686756",

            "lastName": "_"

          },

          "riders": {

            "rider": [

             

            ]

          }

        }

      ]

    }

  }

}

**Comment by vidzi** [comment]
This doesnt have a valid api endpoint

**Comment by ayushmittal29** [comment]
Adding the updated API below:


https://gatewayuat.maxlifeinsurance.com/apimgm/sb/soa/leadmanagement/lead/leadcreatewithrider/v5

And below request:

{

  "request": {

    "header": {

      "soaMsgVersion": "1.0",

      "soaCorrelationId": "49d28623-981b-4e60-8d47-525df4485b6b",

      "soaPassword": "bmVvQDEyMw\u003d\u003d",

      "soaUserId": "NEO123",

      "soaAppId": "NEO"

    },

    "requestData": {

      "createLeadWithRider": [

        {

          "lead": {

            "leadOwnerKey": "1",

            "leadAmount": "50000",

            "leadName": "Gdgfd",

            "statusCodeDisplay": "New Lead",

            "leadAction": "add",

            "applicationStatus": "109",

            "applicationSubStatus": "112",

            "productCode": "TCOTP2",

            "statusCode": "123",

            "product": "",

            "influencerCategory": "Website Direct",

            "influencerCompanyCode": "4",

            "influencerSourceCode": "178",

            "leadSource": "250",

            "ratingKey": "1"

          },

          "proposer": {

            "email": "ddd@gggg.vom",

            "firstName": "Gdgfd",

            "mobilePhone": "9787686756",

            "lastName": "_"

          },

          "riders": {

            "rider": [

             

            ]

          }

        }

      ]

    }

  }

}

**Comment by vidzi** [comment]
```{"request":{"header":{"soaMsgVersion":"1.0","soaCorrelationId":"49d28623-981b-4e60-8d47-525df4485b6b","soaPassword":"bmVvQDEyMw\u003d\u003d","soaUserId":"NEO123","soaAppId":"NEO"},"requestData":{"createLeadWithRider":[{"lead":{"leadOwnerKey":"1","leadAmount":"50000","leadName":"Gdgfd","statusCodeDisplay":"New Lead","leadAction":"add","applicationStatus":"109","applicationSubStatus":"112","productCode":"TCOTP2","statusCode":"123","product":"","influencerCategory":"Website Direct","influencerCompanyCode":"4","influencerSourceCode":"178","leadSource":"250","ratingKey":"1"},"proposer":{"email":"ddd@gggg.vom","firstName":"Gdgfd","mobilePhone":"9787686756","lastName":"_"},"riders":{"rider":[]}}]}}}```
