### ISSUE TITLE
Webview is opening 100%

### ISSUE THREAD

**Issue by tunetopj** [scupid-admin/Morph.ai-Support#95]
https://app.morph.ai/#build/conversations/5bbf023fe1a75435f767e0dd
Brand - Morph.ai
In this conversation, the webview is selected at 70% but opening 100%.
Other conversations working fine.

**Comment by deemorph** [comment]
@tunetopj @vidzi 
https://app.morph.ai/#build/conversations/5bbf21fae1a754668af18b3b
^^ Is this the conversation which have issue ?
If yes i checked the data for this in backend, it has correct web view height ratio i.e "tall" (70%). 
```
"cT" : [
		{
			"_id" : null,
			"f" : [
				{
					"c" : "I am sure you are not actually looking to buy the dummy stuff. But in case you are interested, we're here to help.",
					"tFT" : "TITLE",
					"iH" : false,
					"fT" : "Text",
					"_class" : "com.altin.morphbase.message.beans.field.TextField"
				},
				{
					"u" : "http://paypal.me/morphai/99usd",
					"aUId" : false,
					"wbvwHgtRtio" : "TALL",
					"mExs" : false,
					"r" : false,
					"l" : "Pay Now",
					"iH" : false,
					"fT" : "LinkButton",
					"_class" : "com.altin.morphbase.message.beans.field.LinkButtonField"
				}
			],
			"isDeleted" : false
		}
	]
```
I couldn't find any issue in code also. "full" size is only used when "wbvwHgtRtio" is saved as null.

**Comment by tunetopj** [comment]
Yes, it was set for 70% but was opening 100%. But the conversation was changed later.
Cannot reproduce the error, so closing this.
